

    
  module.exports = {
    DB_URI_AFT:process.env.DB_URI_AFT,
    AUTH0_SECRET=process.env.AUTH0_SECRET,
    AUTH0_BASE_URL=process.env.AUTH0_BASE_URL,
    AUTH0_ISSUER_BASE_URL=process.env.AUTH0_ISSUER_BASE_URL,
    AUTH0_CLIENT_ID=process.env.AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET=process.env.AUTH0_CLIENT_SECRET,
    AUTH0_AUDIENCE=process.env. AUTH0_AUDIENCE,
    AUTH0_SCOPE=process.env.UTH0_SCOPE,
    PORTFOLIO_API_URL=process.env.PORTFOLIO_API_URL,
    AUTH0_NAMESPACE=process.env.AUTH0_NAMESPACE,
  };
